spring:
  config:
    activate:
      on-profile: prod
  server:
    port: 8080

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    generate-ddl: false
  sql:
    init:
      mode: never

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ORIGIN}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: '*'
          auth: true
          starttls:
            enable: true

  application:
    security:
      jwt:
        secret-key: ${SECRET_KEY_JWT}
        expiration: 86400000
